apiVersion: v1
kind: Service
metadata:
  name: kjhkhj
  namespace: namespace-workflow-1683700134278
spec:
  type: LoadBalancer
  selector:
    app: kjhkhj
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000